// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Controls whether approvals remain manual or are automatically reviewed.
 */
export type ApprovalReviewPolicy = "manual-only" | "auto-only";
