// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomaticApprovalReviewStatus } from "./AutomaticApprovalReviewStatus";
import type { RiskLevel } from "./RiskLevel";

/**
 * [UNSTABLE] Automatic approval review details for an item.
 */
export type AutomaticApprovalReview = { status: AutomaticApprovalReviewStatus, riskScore: number | null, riskLevel: RiskLevel | null, rationale: string | null, };
