// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

/**
 * [UNSTABLE] Sent when automatic approval review begins for a command execution item.
 */
export type CommandExecutionAutoApprovalReviewStartedNotification = { item: ThreadItem, threadId: string, turnId: string, };
