// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsWatchEventType } from "./FsWatchEventType";

/**
 * Filesystem watch notification emitted for `fs/watch` subscribers.
 */
export type FsChangedNotification = { 
/**
 * Watch identifier returned by `fs/watch`.
 */
watchId: string, 
/**
 * File or directory path associated with this event.
 */
changedPath: string, 
/**
 * Node-style watch event type associated with the change.
 */
eventType: FsWatchEventType, };
