// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request minimal file metadata needed by current Codex clients.
 */
export type FsGetMetadataParams = { 
/**
 * Absolute path to inspect.
 */
path: string, };
