// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List direct child names for a directory.
 */
export type FsReadDirectoryParams = { 
/**
 * Absolute directory path to read.
 */
path: string, };
