// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node-style event type reported by `fs/changed`.
 */
export type FsWatchEventType = "change" | "rename";
