// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UNSTABLE: Guardian assessment status values are part of the evolving app UI surface.
 */
export type GuardianAssessmentStatus = "in_progress" | "approved" | "denied";
