// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UNSTABLE: Guardian risk labels are part of the evolving app UI surface.
 */
export type GuardianRiskLevel = "low" | "medium" | "high";
