// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Whether a pending approval is waiting on manual input or automatic review.
 */
export type ItemApprovalPendingKind = "manualRequest" | "automaticReview";
