// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomaticApprovalReview } from "./AutomaticApprovalReview";
import type { ItemApprovalPendingKind } from "./ItemApprovalPendingKind";
import type { ItemApprovalResolvedBy } from "./ItemApprovalResolvedBy";
import type { ItemApprovalStatus } from "./ItemApprovalStatus";

export type ItemApprovalState = { status: ItemApprovalStatus, pendingKind: ItemApprovalPendingKind | null, resolvedBy: ItemApprovalResolvedBy | null, automaticReview: AutomaticApprovalReview | null, };
