// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { PluginAppSummary } from "./PluginAppSummary";
import type { PluginMcpServerSummary } from "./PluginMcpServerSummary";
import type { PluginSkillSummary } from "./PluginSkillSummary";
import type { PluginSummary } from "./PluginSummary";

export type PluginDetail = { marketplaceName: string, marketplacePath: AbsolutePathBuf, summary: PluginSummary, description: string | null, skills: Array<PluginSkillSummary>, apps: Array<PluginAppSummary>, mcpServers: Array<PluginMcpServerSummary>, };
