// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Risk level assigned by automatic approval review.
 */
export type RiskLevel = "low" | "medium" | "high";
