use std::any::TypeId;
use std::collections::BTreeMap;
use std::collections::HashSet;
use std::io;
use std::path::Path;
use std::path::PathBuf;

use schemars::JsonSchema;
use schemars::r#gen::SchemaSettings;
use schemars::schema::RootSchema;
use serde_json::Map;
use serde_json::Value;
use ts_rs::TS;
use ts_rs::TypeVisitor;

use crate::protocol::RolloutLine;

const GENERATED_TS_HEADER: &str = "// GENERATED CODE! DO NOT MODIFY BY HAND!\n\n";
const TS_RS_NOTE: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n";
const JSON_SCHEMA_FILENAME: &str = "rollout-line.schema.json";
const TYPESCRIPT_FILENAME: &str = "rollout-line.schema.ts";

pub fn default_rollout_line_schema_dir() -> PathBuf {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let codex_rs_dir = manifest_dir.parent().unwrap_or(manifest_dir);
    codex_rs_dir.join("out/rollout-line-schema")
}

pub fn write_rollout_line_schema_artifacts(out_dir: &Path) -> io::Result<()> {
    std::fs::create_dir_all(out_dir)?;

    let schema_path = out_dir.join(JSON_SCHEMA_FILENAME);
    std::fs::write(&schema_path, rollout_line_schema_json()?)?;

    let typescript_path = out_dir.join(TYPESCRIPT_FILENAME);
    std::fs::write(&typescript_path, rollout_line_schema_typescript())?;

    Ok(())
}

fn rollout_line_schema_json() -> io::Result<Vec<u8>> {
    let schema = schema_for_type::<RolloutLine>();
    let value = serde_json::to_value(schema).map_err(io::Error::other)?;
    let value = canonicalize_json(&value);
    serde_json::to_vec_pretty(&value).map_err(io::Error::other)
}

fn rollout_line_schema_typescript() -> String {
    generate_typescript_bundle::<RolloutLine>()
}

fn schema_for_type<T>() -> RootSchema
where
    T: JsonSchema,
{
    SchemaSettings::draft07()
        .with(|settings| {
            settings.option_add_null_type = false;
        })
        .into_generator()
        .into_root_schema_for::<T>()
}

fn canonicalize_json(value: &Value) -> Value {
    match value {
        Value::Array(items) => Value::Array(items.iter().map(canonicalize_json).collect()),
        Value::Object(map) => {
            let mut entries: Vec<_> = map.iter().collect();
            entries.sort_by(|(left, _), (right, _)| left.cmp(right));
            let mut sorted = Map::with_capacity(map.len());
            for (key, child) in entries {
                sorted.insert(key.clone(), canonicalize_json(child));
            }
            Value::Object(sorted)
        }
        _ => value.clone(),
    }
}

fn generate_typescript_bundle<T: TS + 'static + ?Sized>() -> String {
    let mut declarations = BTreeMap::new();
    let mut seen = HashSet::new();
    collect_typescript_declarations::<T>(&mut declarations, &mut seen);

    let body = declarations
        .into_values()
        .collect::<Vec<_>>()
        .join("\n\n")
        .replace("\r\n", "\n")
        .replace('\r', "\n");
    format!("{GENERATED_TS_HEADER}{TS_RS_NOTE}\n{body}\n")
}

fn collect_typescript_declarations<T: TS + 'static + ?Sized>(
    declarations: &mut BTreeMap<PathBuf, String>,
    seen: &mut HashSet<TypeId>,
) {
    let Some(output_path) = T::output_path() else {
        return;
    };
    if !seen.insert(TypeId::of::<T>()) {
        return;
    }

    let mut declaration = String::new();
    if let Some(docs) = T::docs() {
        declaration.push_str(&docs.replace("\r\n", "\n").replace('\r', "\n"));
    }
    declaration.push_str("export ");
    declaration.push_str(&T::decl().replace("\r\n", "\n").replace('\r', "\n"));
    declarations.insert(output_path.components().collect(), declaration);

    let mut visitor = TypeScriptDeclarationCollector { declarations, seen };
    T::visit_dependencies(&mut visitor);
}

struct TypeScriptDeclarationCollector<'a> {
    declarations: &'a mut BTreeMap<PathBuf, String>,
    seen: &'a mut HashSet<TypeId>,
}

impl TypeVisitor for TypeScriptDeclarationCollector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        collect_typescript_declarations::<T>(self.declarations, self.seen);
    }
}
